export const ROUTE_PRIVACY_POLICY_LIST = '@route/ROUTE_PRIVACY_POLICY_LIST';
export const ROUTE_LOCATION_LANGUAGE = '@route/ROUTE_LOCATION_LANGUAGE';
export const ROUTE_SERVICES = '@route/ROUTE_SERVICES';
export const ROUTE_TRANSLATIONS = '@route/ROUTE_TRANSLATIONS';
export const ROUTE_SETTINGS = '@route/ROUTE_SETTINGS';

export const ROUTE_PRIVACY_POLICY = '@route/ROUTE_PRIVACY_POLICY';
export const ROUTE_PRIVACY_POLICY_NO_PUBLISHED_VERSION = '@route/ROUTE_PRIVACY_POLICY_NO_PUBLISHED_VERSION';
export const ROUTE_PRIVACY_POLICY_CREATE = '@route/ROUTE_PRIVACY_POLICY_CREATE';
export const ROUTE_PRIVACY_POLICY_UPDATE = '@route/ROUTE_PRIVACY_POLICY_UPDATE';
export const ROUTE_GPP_UPDATE = '@route/ROUTE_GPP_UPDATE';
export const ROUTE_GPP_CREATE = '@route/ROUTE_GPP_CREATE';

export const ROUTE_PRIVACY_POLICY_VERSION_LIST = '@route/ROUTE_PRIVACY_POLICY_VERSION_LIST';
export const ROUTE_PRIVACY_POLICY_VERSION_CREATE = '@route/ROUTE_PRIVACY_POLICY_VERSION_CREATE';
export const ROUTE_PRIVACY_POLICY_VERSION_UPDATE = '@route/ROUTE_PRIVACY_POLICY_VERSION_UPDATE';

export const ROUTE_SETTINGS_USER = '@route/ROUTE_SETTINGS_USER';

export const ROUTE_HOME = '@route/HOME';
export const ROUTE_LOGIN = '@route/LOGIN';
export const ROUTE_LOGOUT = '@route/LOGOUT';
export const ROUTE_SIGNUP = '@route/SIGNUP';
export const ROUTE_FORGOT_PASSWORD = '@route/FORGOT_PASSWORD';
export const ROUTE_CHANGE_PASSWORD = '@route/CHANGE_PASSWORD';
export const ROUTE_CREATE_PASSWORD = '@route/CREATE_PASSWORD';
export const ROUTE_RESET_PASSWORD = '@route/RESET_PASSWORD';
export const ROUTE_ERROR_400 = '@route/ERROR_400';
export const ROUTE_ERROR_403 = '@route/ERROR_403';
export const ROUTE_ERROR_404 = '@route/ERROR_404';
export const ROUTE_ERROR_500 = '@route/ERROR_500';
export const ROUTE_ERROR_502 = '@route/ERROR_502';
export const ROUTE_ERROR_503 = '@route/ERROR_503';
